baseURL = "https://fallingyang.github.io"
languageCode = "zh-CN"
title = "往事随风的博客"
theme = "maupassant"
toc = true
googleAnalytics = "GA ID"
preserveTaxonomyNames = true
disablePathToLower = true

[author]
  name = "往事随风"

[params]
  author = "往事随风"
  subtitle = "软件工程师|微服务中间件研发|熟悉Java,Go,Rust"
  keywords = "往事随风,博客"
  description = "代码洁癖者,软件架构等"
  busuanzi = true
  [[params.links]]
    title = "容器网络"
    name = "Docker与Kubernetes网络"
    url = "https://github.com/fallingyang/container-networking-docker-kubernetes"
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params.utteranc]
    enable = true
    repo = "fallingyang/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种